<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header class="header">
        <h2>Header</h2>
    </header>
    <main class="main">
        <?php include_once VIEW . $content_view ?>
    </main>
</body>
</html>